version: '3'

services:
  server:
    build: .
    volumes:
      - .:/strongroom_server
    environment:
      POSTGRES_DB: strongroom_db
      POSTGRES_USER: postgres
    ports:
      - "13222:13222"
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /Users/Shun/Documents/Dev/pass/db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
    # Open DB ports to host only for dev, production should use expose only
      - "9876:5432"